### ISSUE TITLE
Backend functionality

### ISSUE THREAD

**Issue by 21Chaano** [Academic-Panic/academic-panic-application#18]
Implement functionality to store users, create sessions, add courses, etc.

**Comment by elwais** [comment]
Partial work for this task has started with adding a username. See #20.

**Comment by elwais** [comment]
ChatGPT examples of interfacing with Prisma can be found in the discussion at #17, which may be useful when it comes to "connecting" UI interactions to database operations.

**Comment by elwais** [comment]
See #17 for work done on courses and #23 for sessions.

**Comment by elwais** [comment]
Largely addressed at the time of writing with sessions implemented.
